"use strict";
require("dotenv").config();

const Telegraf = require("telegraf");
const Telegram = require("telegraf/telegram");
const extra = require("telegraf/extra");

const replies = [
  "WAS, EIN BRUDIMOMENT?",
  "GEHT IN DECKUNG DAS IST EIN BRUDIMOMENT!",
  "HALLO BRUDIMOMENTMELDESTELLE? ES GIBT EINEN BRUDIMOMENT ZU MELDEN",
  "BRUDI WAS IST DAS DENN",
  "BRUDI, HAST DU EINEN MOMENT?",
  "DAS IST EIN BRUDIMOMENT",
  "ACHTUNG ACHTUNG DAS HIER IST EIN BRUDIMOMENT",
  "HALLO BRUDIMOMENTMEDLESTELLE HIER, IHR BRUDIMOMENT IST EINGEGANGEN",
  "DAS IST OHNE ZWEIFEL EIN WAHRLICHER BRUDIMOMENT",
  "HIER IST DIE BRUDIMOMENTMELDESTELLE. WIR HABEN HIER EINEN BRUDIMOMENT",
  "WILLKOMMEN BEI DER BRUDIMOMENTMELDESTELLE, GEBEN SIE UNS EINEN MOMENT (BRUDI)",
  "DAS HIER IST DIE BRUDIMOMENTMELDESTELLE, ES SCHEINT ALS HÄTTEN WIR ES MIT EINEM BRUDIMOMENT ZU TUN",
  "DIE BRUDIMOMENTMELDESTELLE HAT IHREN BRUDIMOMENT ZUR KENNTNIS GENOMMEN",
  "ABSENDER: BRUDIMOMENTMELDESTELLE\nBETREFF: BRUDIMOMENT",
  "VORSICHT, ES BEFINDET SICH EIN BRUDIMOMENT UNTER UNS",
  "IST DAS DENN ZU GLAUBEN? EIN BRUDIMOMENT!",
  "EPISCHER BRUDIMOMENT",
  "WER KENNT DIESEN BRUDIMOMENT 😂😂😂😂",
  "STARKER BRUDIMOMENT",
  "HIER SPRICHT DIE BRUDIMOMENTMELDESTELLE, HIER LIEGT EIN BRUDIMOMENT VOR.",
  "MÖCHTE JEMAND EINEN BRUDIMOMENT MELDEN?",
  "HALLO BRUDIMOMENT? IST ANGENOMMEN.",
  "SIE HABEN BEI UNS SOEBEN EINEN BRUDIMOMENT GEMELDET.",
  "IHRE MELDUNG WURDE BEARBEITET UND ALS BRUDIMOMENT EINGESTUFT.",
  "EIN NEUER BRUDIMOMENT? JETZT 0800-BRUDIMOMENT ANRUFEN!!",
  "TRAURIGER BRUDIMOMENT",
  "LUSTIGER BRUDIMOMENT",
  "SOEBEN ERREICHEN UNS MELDUNGEN ÜBER EINEN BRUDIMOMENT",
  "EXPERTEN WARNEN VOR EINEM BRUDIMOMENT",
  "ERNSTER BRUDIMOMENT",
  "ENTSCHULDIGUNG, HABEN SIE EINEN BRUDIMOMENT ZEIT?",
  "ZEUGEN BERICHTETEN VON EINEM BRUDIMOMENT",
  "DIAGNOSE: BRUDIMOMENT.",
  "BRUDIMOMENT.\nBRUDI. MOMENT."
];

const bot = new Telegraf(process.env.BOT_TOKEN);
const telegram = new Telegram(process.env.BOT_TOKEN);
bot.start(ctx => ctx.reply("Bruder muss los."));
bot.command("brudimoment", ctx => {
  ctx.reply(replies[Math.floor(Math.random() * replies.length)]);
});
console.log("Bruder muss los...");
bot.launch();
