"use strict";
require("dotenv").config();

const Telegraf = require("telegraf");

const replies = [
  "WAS, EIN BRUDIMOMENT?",
  "GEHT IN DECKUNG DAS IST EIN BRUDIMOMENT!",
  "HALLO BRUDIMOMENTMELDESTELLE? ES GIBT EINEN BRUDIMOMENT ZU MELDEN",
  "BRUDI WAS IST DAS DENN",
  "BRUDI, HAST DU EINEN MOMENT?",
  "DAS IST EIN BRUDIMOMENT",
  "ACHTUNG ACHTUNG DAS HIER IST EIN BRUDIMOMENT",
  "HALLO BRUDIMOMENTMEDLESTELLE HIER, IHR BRUDIMOMENT IST EINGEGANGEN",
  "DAS IST OHNE ZWEIFEL EIN WAHRLICHER BRUDIMOMENT",
  "HIER IST DIE BRUDIMOMENTMELDESTELLE. WIR HABEN HIER EINEN BRUDIMOMENT",
  "WILLKOMMEN BEI DER BRUDIMOMENTMELDESTELLE, GEBEN SIE UNS EINEN MOMENT (BRUDI)",
  "DAS HIER IST DIE BRUDIMOMENTMELDESTELLE, ES SCHEINT ALS HÄTTEN WIR ES MIT EINEM BRUDIMOMENT ZU TUN",
  "DIE BRUDIMOMENTMELDESTELLE HAT IHREN BRUDIMOMENT ZUR KENNTNIS GENOMMEN",
  "ABSENDER: BRUDIMOMENTMELDESTELLE\nBETREFF: BRUDIMOMENT",
  "VORSICHT, ES BEFINDET SICH EIN BRUDIMOMENT UNTER UNS",
  "IST DAS DENN ZU GLAUBEN? EIN BRUDIMOMENT!",
  "EPISCHER BRUDIMOMENT",
  "WER KENNT DIESEN BRUDIMOMENT 😂😂😂😂",
  "STARKER BRUDIMOMENT",
  "HIER SPRICHT DIE BRUDIMOMENTMELDESTELLE, HIER LIEGT EIN BRUDIMOMENT VOR.",
  "MÖCHTE JEMAND EINEN BRUDIMOMENT MELDEN?",
  "HALLO BRUDIMOMENT? IST ANGENOMMEN.",
  "SIE HABEN BEI UNS SOEBEN EINEN BRUDIMOMENT GEMELDET.",
  "IHRE MELDUNG WURDE BEARBEITET UND ALS BRUDIMOMENT EINGESTUFT.",
  "EIN NEUER BRUDIMOMENT? JETZT 0800-BRUDIMOMENT ANRUFEN!!",
  "TRAURIGER BRUDIMOMENT",
  "LUSTIGER BRUDIMOMENT",
  "SOEBEN ERREICHEN UNS MELDUNGEN ÜBER EINEN BRUDIMOMENT",
  "EXPERTEN WARNEN VOR EINEM BRUDIMOMENT",
  "ERNSTER BRUDIMOMENT",
  "ENTSCHULDIGUNG, HABEN SIE EINEN BRUDIMOMENT ZEIT?",
  "ZEUGEN BERICHTETEN VON EINEM BRUDIMOMENT",
  "DIAGNOSE: BRUDIMOMENT.",
  "BRUDIMOMENT.\nBRUDI. MOMENT.",
  "HEFTIGER BRUDIMOMENT",
  "🚨 BRUDIMOMENTALARM 🚨",
  "WAS EIN BRUDIMOMENT HAHA 😂👌",
  "DIESER MOMENT WENN BRUDIMOMENT",
  "ES BESTEHT GEFAHR VOR EINEM BRUDIMOMENT",
  "DAS IST EIN NOTFALL! ES GAB EINEN BRUDIMOMENT.",
  "stiller brudimoment.",
  "DIESER BRUDIMOMENT IST ANDERS ALS ANDERE",
  "DER BRUDIMOMENTPEGEL SCHLÄGT AUS",
  "FÜLLEN SIE BITTE DAS ANTRAGSFORMULAR ZUR BRUDIMOMENTMELDUNG AUS DANKE",
  "IST ES ETWA SCHON WIEDER ZEIT FÜR EINEN BRUDIMOMENT??"
];

const bot = new Telegraf(process.env.BOT_TOKEN);

bot.start(ctx => ctx.reply("Bruder muss los."));

bot
  .command("brudimoment", ctx => {
    let replyTo = ctx.message.reply_to_message;

    let reply = replies[Math.floor(Math.random() * replies.length)];

    let options = replyTo ? { reply_to_message_id: replyTo.message_id } : {};

    if (Math.random() < 0.1) {
      ctx.replyWithAudio("https://www.myinstants.com/media/sounds/movie_1.mp3");
      reply = "EIN SELTENER BRUDIMOMENT 😱😱";
    }

    ctx.reply(reply, options);

    if (replyTo) {
      ctx.deleteMessage(ctx.message_id).catch(e => {
        // was willste machen ¯\_(ツ)_/¯
        ctx.reply("(brudi brauch löschrechte)");
        console.log(e);
      });
    }
  })
  .catch(e => {
    console.log(e);
  });

console.log("Bruder muss los...");

bot.launch();
